
INSERT INTO ORDERS(PRODUCTS, ID_USER, STATUS, CREATED_AT, UPDATED_AT) VALUES('[{"productId": 1, "quantity": 10}, {"productId": 2, "quantity": 6}]', 1, 'APPROVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO ORDERS(PRODUCTS, ID_USER, STATUS, CREATED_AT, UPDATED_AT) VALUES('[{"productId": 3, "quantity": 50}, {"productId": 1, "quantity": 5}]', 2, 'REJECTED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
