version: "3"

networks:
  sales-network:
    driver: bridge

services:

  auth-db:
    image: postgres:11
    container_name: auth-db
    networks:
      - sales-network
    restart: always
    environment:
      - POSTGRES_DB=auth-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432

  product-db:
    image: postgres:11
    container_name: product-db
    networks:
      - sales-network
    restart: always
    environment:
      - POSTGRES_DB=product-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    ports:
      - 5433:5432

  sales-db:
    image: postgres:11
    container_name: sales-db
    networks:
      - sales-network
    restart: always
    environment:
      - POSTGRES_DB=sales-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    ports:
      - 5434:5432

  sales-rabbit:
    image: rabbitmq:3-management
    container_name: sales-rabbit
    networks:
      - sales-network
    ports:
      - 5672:5672
      - 25676:25676
      - 15672:15672

  auth-api:
    build: './auth-api'
    container_name: auth-api
    networks:
      - sales-network
    depends_on:
      - auth-db
    environment:
      - PORT=8080
      - API_SECRET=bWluaGFzZW5oYXNlY3JldGFESUpPUFdRSk9JRGpvaXh3c2RqYW9pYWRzamlvZHF3amlvMA==
      - DB_HOST=auth-db
      - DB_NAME=auth-db
      - DB_USER=admin
      - DB_PASSWORD=123456
      - DB_PORT=5432
    ports:
      - 8080:8080

  product-api:
    build: './product-api'
    container_name: product-api
    networks:
      - sales-network
    depends_on:
      - product-db
      - sales-rabbit
    environment:
      - PORT=8081
      - API_SECRET=bWluaGFzZW5oYXNlY3JldGFESUpPUFdRSk9JRGpvaXh3c2RqYW9pYWRzamlvZHF3amlvMA==
      - DB_HOST=product-db
      - DB_NAME=product-db
      - DB_USER=admin
      - DB_PASSWORD=123456
      - DB_PORT=5432
      - RABBIT_MQ_HOST=sales-rabbit
      - RABBIT_MQ_PORT=5672
      - RABBIT_MQ_USER=guest
      - RABBIT_MQ_PASSWORD=guest
      - SALES_HOST=sales-api
      - SALES_PORT=8082
    ports:
      - 8081:8081

  sales-api:
    build: './sales-api'
    container_name: sales-api
    networks:
      - sales-network
    depends_on:
      - sales-db
      - sales-rabbit
    environment:
      - PORT=8082
      - API_SECRET=bWluaGFzZW5oYXNlY3JldGFESUpPUFdRSk9JRGpvaXh3c2RqYW9pYWRzamlvZHF3amlvMA==
      - DB_HOST=sales-db
      - DB_NAME=sales-db
      - DB_USER=admin
      - DB_PASSWORD=123456
      - DB_PORT=5432
      - RABBIT_MQ_HOST=sales-rabbit
      - RABBIT_MQ_PORT=5672
      - RABBIT_MQ_USER=guest
      - RABBIT_MQ_PASSWORD=guest
      - PRODUCT_HOST=product-api
      - PRODUCT_PORT=8081
    ports:
      - 8082:8082
