INSERT INTO CATEGORY(DESCRIPTION) VALUES('Comic Books');
INSERT INTO CATEGORY(DESCRIPTION) VALUES('Movies');
INSERT INTO CATEGORY(DESCRIPTION) VALUES('Books');

INSERT INTO SUPPLIER(NAME) VALUES('Amazon');
INSERT INTO SUPPLIER(NAME) VALUES('Reseller');

INSERT INTO PRODUCT(NAME, QUANTITY_AVAILABLE, ID_SUPPLIER, ID_CATEGORY, CREATED_AT) VALUES('Avengers', 1, 2, 1, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT(NAME, QUANTITY_AVAILABLE, ID_SUPPLIER, ID_CATEGORY, CREATED_AT) VALUES('Batman', 50, 1, 2, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT(NAME, QUANTITY_AVAILABLE, ID_SUPPLIER, ID_CATEGORY, CREATED_AT) VALUES('Curso Java8', 100, 1, 3, CURRENT_TIMESTAMP);
